# 编译右半单块键盘，不用分体，蓝牙+有线，使用ortho20_20_right
name: ortho20_20_right
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build firmware
        uses: zmkfirmware/zmk-build-action@v2
        with:
          board: nice_nano_v2
          shield: ortho20_20_right
